# Generated by Django 5.0.2 on 2025-09-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
