# Generated by Django 5.2.6 on 2025-09-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_activitylog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
